Repository bandibook/bandibook, pull requests merged in 2024-12, with the labels that each got.

#115 [DOP] Week2
  notes/book/data-oriented-programming/만혁/ch3.mdx
  notes/book/data-oriented-programming/만혁/ch4.mdx
  notes/book/data-oriented-programming/우석/ch3.mdx
  notes/book/data-oriented-programming/우석/ch4.mdx
Labels: DOP

#116 [모던 리액트 Deep Dive] ch12 김도은
  notes/book/react-deep-dive/도은/ch12.mdx
  notes/book/react-deep-dive/준영/ch12.mdx
Labels: 리액트 Deep Dive

#117 feat: 재배포를 수동으로 trigger할 수 있는 workflow 추가
  .github/workflows/depoly.yml
Labels: 🌎 기능

#119 fix: depoly workflow 실행 시 build cache를 사용하지 않도록
  .github/workflows/depoly.yml
Labels: 🌎 기능

#120 feat: pretendard 폰트 적용 및 스타일 보정
  components/Figure/Figure.tsx
  components/Figure/index.ts
  components/Figure/styles.ts
  components/index.ts
  components/utils/RenderWhenPrimitive.tsx
  pages/_app.tsx
  pages/book/index.mdx
  pages/book/react-deep-dive/ch6.mdx
  pages/styles.css
  theme.config.jsx
  tsconfig.json
Labels: 🌎 기능

#122 [DOP] week3 ch5
  notes/book/data-oriented-programming/만혁/ch5.mdx
Labels: DOP

#124 [모던 리액트 Deep Dive] ch14 김도은
  notes/book/react-deep-dive/도은/ch14.mdx
  notes/book/react-deep-dive/준영/ch14.mdx
Labels: 리액트 Deep Dive

#137 [DOP] week4
  notes/book/data-oriented-programming/만혁/ch6.mdx
  notes/book/data-oriented-programming/만혁/ch7.mdx
  notes/book/data-oriented-programming/우석/ch6.mdx
  notes/book/data-oriented-programming/우석/ch7.mdx
Labels: DOP

#135 [🌎 Feature] 경로에 맞는 코드 오너 지정
  .github/CODEOWNERS
Labels: 10000-bagger

#138 [DOP] week5
  notes/book/data-oriented-programming/우석/ch8.mdx
  notes/book/data-oriented-programming/우석/ch9.mdx
Labels: DOP
