Repository bandibook/bandibook, pull requests merged in 2024-07, with the labels that each got.

#36 [모던 리액트 Deep Dive] ch2~3 김도은
  notes/react-deep-dive/도은/ch2.mdx
  notes/react-deep-dive/도은/ch3.mdx
Labels: 리액트 Deep Dive

#39 [모던 리액트 Deep Dive] ch2~3 허준영
  notes/react-deep-dive/준영/ch2.mdx
  notes/react-deep-dive/준영/ch3.mdx
Labels: 리액트 Deep Dive

#40 [모던 리액트 Deep Dive] ch2-3 week 정리
  notes/react-deep-dive/도은/ch2.mdx
  notes/react-deep-dive/도은/ch3.mdx
  notes/react-deep-dive/준영/ch2.mdx
  notes/react-deep-dive/준영/ch3.mdx
Labels: 🚀 week 정리

#38 [쏙쏙 들어오는 함수형 코딩] ch6 ~ ch7 한만혁
  notes/grokking-simplicity/만혁/ch6.mdx
  notes/grokking-simplicity/만혁/ch7.mdx
Labels: 쏙쏙 함수형 코딩

#42 [쏙쏙 들어오는 함수형 코딩] ch6 ~ ch7 권우석
  notes/grokking-simplicity/우석/ch6.mdx
  notes/grokking-simplicity/우석/ch7.mdx
Labels: 쏙쏙 함수형 코딩

#43 chore: 메뉴 접혀서 렌더링 되도록 config 추가
  theme.config.jsx
Labels: chore

#45 [쏙쏙 들어오는 함수형 코딩] ch8 ~ ch9 권우석
  notes/grokking-simplicity/우석/ch8.mdx
  notes/grokking-simplicity/우석/ch9.mdx
Labels: 쏙쏙 함수형 코딩

#46 [쏙쏙 들어오는 함수형 코딩] ch8 ~ ch9 한만혁
  notes/grokking-simplicity/만혁/ch8.mdx
  notes/grokking-simplicity/만혁/ch9.mdx
Labels: 쏙쏙 함수형 코딩
